# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Rahmat's Blog 🌵
full_name: Rahmat Nazali Salimi
email: rahmatnazali95@gmail.com
description: Rahmat's personal blog for documenting his life and career as a Software Developer.
baseurl: ""
url: "https://rahmatnazali.github.io"
google_analytics: G-14GYDRDZNH
disqus:
  shortname: rahmatnazali
  enable: false

github_username:  "rahmatnazali"
youtube_username:  "@trubusthecactus"
twitter_username: "rahmatnazali95"
linkedin_username: "rahmat-nazali-salimi-43391a13b"

header_pages:
  - profile.markdown
  - about.markdown

theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - dev.sh
  - staging.sh
